language: php

dist: trusty

sudo: false

cache:
    directories:
        - ~/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 7.2
    - php: 7.2
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

install:
    - composer install --no-interaction --prefer-dist ${COMPOSER_FLAGS}

script:
    - composer validate --strict
    - bin/ecs check src
    - bin/phpstan analyse -c phpstan.neon -l max src/
    - bin/simple-phpunit