language: php

dist: trusty

sudo: false

php:
    - 7.1
    - 7.2

cache:
    directories:
        - ~/.composer/cache

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - composer install --no-interaction --prefer-dist ${COMPOSER_FLAGS}

script:
    - composer validate --strict
    - bin/ecs check src
    - bin/phpstan analyse -c phpstan.neon -l max src/
    - bin/simple-phpunit